use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use time::OffsetDateTime;

use crate::game::{
    calibration::CalibrationBaseline,
    evolution::Stage,
    metabolism::{Mood, RhythmProfile},
};
use crate::pet::generation::Species;

const CURRENT_SCHEMA_VERSION: u32 = 1;

/// A timestamped character-driven feed entry generated by the narration system.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NarrativeEvent {
    pub observed_at: OffsetDateTime,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PetState {
    pub schema_version: u32,
    pub pet: PetIdentity,
    pub stage: Stage,
    pub xp: f64,
    pub lifetime_effective_tokens: f64,
    pub vitals: Vitals,
    #[serde(default)]
    pub calibration: CalibrationBaseline,
    #[serde(default)]
    pub rhythm: RhythmProfile,
    /// Destination stage of every transition the pet has visited, in the
    /// order they fired. Used by the activity feed and the watch overlay
    /// to render evolution moments. Serialized as a list of stage strings
    /// (`["s0","s1",...]`); also accepts the pre-0.2 legacy format
    /// (`["s0->s1","s1->s2",...]`) when loading existing state files.
    #[serde(default, deserialize_with = "deserialize_seen_stage_transitions")]
    pub seen_stage_transitions: Vec<Stage>,
    /// Character-driven feed entries. The custom deserializer accepts both the
    /// new `[{observed_at, text}]` shape and the legacy `["string"]` shape so
    /// existing state.json files keep loading cleanly. Legacy strings are
    /// discarded (recent_events is ephemeral, trimmed to 20 entries).
    #[serde(default, deserialize_with = "deserialize_narrative_events_backcompat")]
    pub recent_events: Vec<NarrativeEvent>,
    /// Last observed mood — used to detect mood transitions across polls.
    #[serde(default)]
    pub last_seen_mood: Option<Mood>,
    /// Vitals snapshot from the previous poll — used to detect vital threshold crossings.
    #[serde(default)]
    pub previous_vitals: Option<Vitals>,
    /// When the last idle narration was emitted — prevents re-firing within 6 hours.
    #[serde(default)]
    pub last_idle_narration_at: Option<OffsetDateTime>,
    pub created_at: OffsetDateTime,
    pub last_updated_at: OffsetDateTime,
    pub last_usage_poll_at: Option<OffsetDateTime>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PetIdentity {
    pub seed: String,
    pub generated_species: Species,
    pub accepted_name: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Vitals {
    pub fed: f64,
    pub happiness: f64,
    pub energy: f64,
}

pub struct StateStore {
    path: PathBuf,
}

impl PetState {
    pub fn new_for_test(seed: &str, name: &str) -> Self {
        let now = OffsetDateTime::UNIX_EPOCH;
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            pet: PetIdentity {
                seed: seed.to_string(),
                generated_species: Species::Fuzz,
                accepted_name: name.to_string(),
            },
            stage: Stage::S0,
            xp: 0.0,
            lifetime_effective_tokens: 0.0,
            calibration: CalibrationBaseline::default(),
            rhythm: RhythmProfile::default(),
            seen_stage_transitions: Vec::new(),
            recent_events: Vec::new(),
            last_seen_mood: None,
            previous_vitals: None,
            last_idle_narration_at: None,
            vitals: Vitals {
                fed: 70.0,
                happiness: 70.0,
                energy: 70.0,
            },
            created_at: now,
            last_updated_at: now,
            last_usage_poll_at: None,
        }
    }
}

impl StateStore {
    pub fn new(path: PathBuf) -> Self {
        Self { path }
    }

    pub fn load(&self) -> crate::error::Result<Option<PetState>> {
        if !self.path.exists() {
            return Ok(None);
        }

        let text = std::fs::read_to_string(&self.path)?;
        let value: serde_json::Value = serde_json::from_str(&text).map_err(|err| {
            crate::error::GlorpError::Message(format!(
                "malformed state.json at {}: {err}",
                self.path.display()
            ))
        })?;

        let schema_version = value
            .get("schema_version")
            .and_then(serde_json::Value::as_u64)
            .ok_or_else(|| {
                crate::error::GlorpError::Message(
                    "malformed state.json: missing numeric schema_version".into(),
                )
            })?;

        if schema_version != u64::from(CURRENT_SCHEMA_VERSION) {
            return Err(crate::error::GlorpError::Message(format!(
                "unsupported schema version {schema_version} in state.json"
            )));
        }

        serde_json::from_value(value).map(Some).map_err(|err| {
            crate::error::GlorpError::Message(format!(
                "malformed state.json at {}: {err}",
                self.path.display()
            ))
        })
    }

    pub fn save(&self, state: &PetState) -> crate::error::Result<()> {
        if state.schema_version != CURRENT_SCHEMA_VERSION {
            return Err(crate::error::GlorpError::Message(format!(
                "unsupported schema version {} in state save",
                state.schema_version
            )));
        }

        let parent = self.path.parent().ok_or_else(|| {
            crate::error::GlorpError::Message(format!(
                "state path has no parent directory: {}",
                self.path.display()
            ))
        })?;
        std::fs::create_dir_all(parent)?;

        let text = serde_json::to_string_pretty(state)?;

        // Atomic save: write to a sibling temp file in the same directory, fsync
        // its contents to disk, then rename into place. POSIX `rename(2)` is
        // atomic on the same filesystem; `NamedTempFile::persist` uses
        // `MoveFileExA` on Windows, which is atomic for same-volume moves.
        // `NamedTempFile` auto-deletes the temp file on drop if persist fails,
        // so the directory is not littered with `state.json.tmp.*` files when
        // any step errors out.
        let mut tmp = tempfile::Builder::new()
            .prefix("state.json.tmp.")
            .tempfile_in(parent)?;
        {
            use std::io::Write;
            tmp.as_file_mut().write_all(text.as_bytes())?;
            tmp.as_file_mut().sync_all()?;
        }
        tmp.persist(&self.path).map_err(|err| err.error)?;
        Ok(())
    }

    pub fn delete(&self) -> crate::error::Result<()> {
        match std::fs::remove_file(&self.path) {
            Ok(()) => Ok(()),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(err) => Err(err.into()),
        }
    }
}

#[doc(hidden)]
pub struct PetStateFixture {
    state: PetState,
}

impl PetStateFixture {
    pub fn named(name: &str) -> Self {
        Self {
            state: PetState::new_for_test("fixture-seed", name),
        }
    }

    pub fn with_stage(mut self, stage: Stage) -> Self {
        self.state.stage = stage;
        self
    }

    pub fn with_recent_event(mut self, event: &str) -> Self {
        self.state.recent_events.push(NarrativeEvent {
            observed_at: OffsetDateTime::UNIX_EPOCH,
            text: event.to_string(),
        });
        self
    }

    fn into_state(self) -> PetState {
        self.state
    }
}

#[doc(hidden)]
pub fn write_state_for_test(
    dir: &std::path::Path,
    fixture: PetStateFixture,
) -> crate::error::Result<()> {
    let paths = crate::paths::AppPaths::from_config_dir(dir.to_path_buf());
    paths.ensure()?;
    StateStore::new(paths.state_file).save(&fixture.into_state())
}

// Backwards-compat deserializer for `recent_events`.
//
// Accepts either the new `[{observed_at, text}]` shape or the legacy
// `["string"]` shape. Legacy strings are silently discarded — recent_events
// is ephemeral (trimmed to 20 entries) so losing them on first load of an
// older state.json is acceptable.
fn deserialize_narrative_events_backcompat<'de, D>(
    deserializer: D,
) -> Result<Vec<NarrativeEvent>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::de::{SeqAccess, Visitor};
    use std::fmt;

    struct NarrativeEventVisitor;

    impl<'de> Visitor<'de> for NarrativeEventVisitor {
        type Value = Vec<NarrativeEvent>;

        fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
            formatter.write_str("an array of NarrativeEvent objects or legacy strings")
        }

        fn visit_seq<A: SeqAccess<'de>>(self, mut seq: A) -> Result<Self::Value, A::Error> {
            let mut events = Vec::new();
            while let Some(value) = seq.next_element::<serde_json::Value>()? {
                match value {
                    serde_json::Value::Object(_) => {
                        if let Ok(event) = serde_json::from_value::<NarrativeEvent>(value) {
                            events.push(event);
                        }
                        // silently skip malformed objects
                    }
                    serde_json::Value::String(_) => {
                        // Legacy string entries — discard.
                    }
                    _ => {
                        // Ignore unexpected shapes.
                    }
                }
            }
            Ok(events)
        }
    }

    deserializer.deserialize_seq(NarrativeEventVisitor)
}

// Backwards-compat deserializer for `seen_stage_transitions`.
//
// Pre-0.2 state files stored each transition as a `"from->to"` pair string
// (e.g. `"s0->s1"`); 0.2+ stores destination stages directly (`"s1"`). Both
// representations carry the same information for the only consumer (the
// activity feed / evolution overlay), since stages advance monotonically.
// We accept either on load so existing users keep their evolution history;
// the next save rewrites the field in the new shape.
fn deserialize_seen_stage_transitions<'de, D>(deserializer: D) -> Result<Vec<Stage>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use std::str::FromStr;
    let raw: Vec<String> = Vec::deserialize(deserializer)?;
    raw.into_iter()
        .map(|entry| {
            let destination = entry.split_once("->").map_or(entry.as_str(), |(_, to)| to);
            Stage::from_str(destination).map_err(serde::de::Error::custom)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn pet_state_deserializes_legacy_string_stage_format() {
        // Existing users' state.json files store `stage`, `generated_species`,
        // and `mood`-adjacent fields as the same lowercase strings the typed
        // enums now serialize to. This test locks the wire format so the
        // typed-enum refactor never accidentally renames the JSON keys.
        // `time` crate's default serde representation is a tuple
        // `[year, ordinal_day, hour, minute, second, nanos, offset_hours, offset_minutes, offset_seconds]`.
        // Real state.json files on disk use exactly this shape.
        let json = r#"{
            "schema_version": 1,
            "pet": {
                "seed": "legacy-seed",
                "generated_species": "ghost",
                "accepted_name": "casper"
            },
            "stage": "s2",
            "xp": 0.5,
            "lifetime_effective_tokens": 12345.0,
            "vitals": {"fed": 70.0, "happiness": 80.0, "energy": 60.0},
            "calibration": {"daily_effective_tokens": 100000.0},
            "rhythm": {"active_hours": [false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false], "weekend_activity_weight": 0.45},
            "seen_stage_transitions": ["s0", "s1", "s2"],
            "recent_events": [],
            "created_at": [2026, 121, 0, 0, 0, 0, 0, 0, 0],
            "last_updated_at": [2026, 129, 0, 0, 0, 0, 0, 0, 0],
            "last_usage_poll_at": null
        }"#;
        let state: PetState = serde_json::from_str(json).expect("legacy JSON must deserialize");
        assert_eq!(state.stage, Stage::S2);
        assert_eq!(state.pet.generated_species, Species::Ghost);
        assert_eq!(
            state.seen_stage_transitions,
            vec![Stage::S0, Stage::S1, Stage::S2]
        );
    }

    #[test]
    fn pet_state_deserializes_pre_0_2_seen_stage_transitions_pair_format() {
        // Pre-0.2 state.json files stored seen_stage_transitions as `from->to`
        // pair strings; we must keep loading those without losing the user's
        // evolution history. The custom deserializer parses the destination
        // half of each pair.
        let json = r#"{
            "schema_version": 1,
            "pet": {
                "seed": "old-seed",
                "generated_species": "fuzz",
                "accepted_name": "buddy"
            },
            "stage": "s3",
            "xp": 0.1,
            "lifetime_effective_tokens": 0.0,
            "vitals": {"fed": 70.0, "happiness": 80.0, "energy": 60.0},
            "calibration": {"daily_effective_tokens": 100000.0},
            "rhythm": {"active_hours": [false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false], "weekend_activity_weight": 0.45},
            "seen_stage_transitions": ["s0->s1", "s1->s2", "s2->s3"],
            "recent_events": [],
            "created_at": [2026, 121, 0, 0, 0, 0, 0, 0, 0],
            "last_updated_at": [2026, 129, 0, 0, 0, 0, 0, 0, 0],
            "last_usage_poll_at": null
        }"#;
        let state: PetState =
            serde_json::from_str(json).expect("legacy pair-format JSON must deserialize");
        assert_eq!(
            state.seen_stage_transitions,
            vec![Stage::S1, Stage::S2, Stage::S3],
            "legacy `from->to` entries should yield the destination stages"
        );
    }

    #[test]
    fn pet_state_serializes_to_legacy_string_format() {
        // The on-disk format must remain readable by older binaries (and by
        // hand-edited JSON). Round-trip through serde_json::Value so we can
        // check the exact string shape without depending on field ordering.
        let mut state = PetState::new_for_test("seed", "buddy");
        state.stage = Stage::S3;
        state.pet.generated_species = Species::Mech;
        state.seen_stage_transitions = vec![Stage::S0, Stage::S1];

        let value: serde_json::Value = serde_json::to_value(&state).unwrap();
        assert_eq!(value["stage"], serde_json::Value::String("s3".into()));
        assert_eq!(
            value["pet"]["generated_species"],
            serde_json::Value::String("mech".into())
        );
        assert_eq!(
            value["seen_stage_transitions"],
            serde_json::json!(["s0", "s1"])
        );
    }

    fn tmp_files_in(dir: &std::path::Path) -> Vec<PathBuf> {
        std::fs::read_dir(dir)
            .unwrap()
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|path| {
                path.file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.starts_with("state.json.tmp."))
            })
            .collect()
    }

    #[test]
    fn save_leaves_no_temp_files_behind() {
        let dir = tempdir().unwrap();
        let store = StateStore::new(dir.path().join("state.json"));
        store
            .save(&PetState::new_for_test("seed-1", "buddy"))
            .unwrap();
        assert!(
            tmp_files_in(dir.path()).is_empty(),
            "save should not leak temp files: {:?}",
            tmp_files_in(dir.path())
        );
    }

    #[test]
    fn load_ignores_stray_temp_files_in_the_state_directory() {
        let dir = tempdir().unwrap();
        let store = StateStore::new(dir.path().join("state.json"));
        let original = PetState::new_for_test("seed-2", "kit");
        store.save(&original).unwrap();

        // Hand-write a leftover that resembles a crash mid-save from a previous
        // run. `load()` must read `state.json` and not be tripped by siblings.
        let stray = dir.path().join("state.json.tmp.99999");
        std::fs::write(&stray, b"garbage that is not json").unwrap();

        let loaded = store.load().unwrap().expect("state.json should load");
        assert_eq!(loaded, original);
        assert!(stray.exists(), "load must not touch foreign temp files");
    }

    #[test]
    fn load_rejects_corrupted_destination_file() {
        // This documents the invariant the atomic save protects: if the
        // destination file is ever partially written, `load` surfaces an error
        // rather than returning a half-state. Atomic rename ensures the real
        // pipeline never produces such a file, but the detector must stay sharp.
        let dir = tempdir().unwrap();
        let store = StateStore::new(dir.path().join("state.json"));
        store
            .save(&PetState::new_for_test("seed-3", "scrap"))
            .unwrap();
        std::fs::write(dir.path().join("state.json"), b"{\"schema_versi").unwrap();

        let err = store.load().expect_err("corrupted state.json must error");
        assert!(
            matches!(err, crate::error::GlorpError::Message(ref msg) if msg.contains("malformed state.json")),
            "expected malformed-json error, got: {err:?}"
        );
    }
}
