use crate::commands::watch::build_watch_view_model_at;
use crate::dev_preview::frame::{frame_from_buffer, PreviewFrame};
use crate::dev_preview::scenarios::PreviewRenderContext;
use crate::error::Result;
use crate::game::evolution::Stage;
use crate::pet::generation::Species;
use crate::storage::{
    state::{
        EarnedHabitatProp, HabitatPropId, HabitatPropSource, NarrativeEvent, PetState, Vitals,
    },
    usage_store::{NormalizedUsageEvent, UsageStore},
};
use crate::tui::layout::render_watch_frame_with_layout;
use crate::tui::render_context::{RenderContext, WatchClock};
use crate::tui::{component::layout_watch_with_context, component::preview_layout};
use ratatui::backend::TestBackend;
use ratatui::layout::Rect;
use ratatui::Terminal;
use std::path::Path;
use time::{Duration, OffsetDateTime, UtcOffset};

pub fn watch_frames(ctx: &PreviewRenderContext, scratch_dir: &Path) -> Result<Vec<PreviewFrame>> {
    std::fs::create_dir_all(scratch_dir)?;

    Ok(vec![
        render_watch_frame(
            "watch-wide-normal",
            "Watch Wide Normal",
            120,
            32,
            ctx,
            scratch_dir,
        )?,
        render_watch_frame(
            "watch-tall-wide",
            "Watch Tall Wide",
            180,
            50,
            ctx,
            scratch_dir,
        )?,
        render_watch_frame(
            "watch-compact-normal",
            "Watch Compact Normal",
            72,
            24,
            ctx,
            scratch_dir,
        )?,
    ])
}

pub(crate) struct WatchFrameFixture<'a> {
    pub id: &'a str,
    pub title: &'a str,
    pub width: u16,
    pub height: u16,
    pub state: &'a PetState,
    pub now: OffsetDateTime,
}

fn render_watch_frame(
    id: &str,
    title: &str,
    width: u16,
    height: u16,
    ctx: &PreviewRenderContext,
    scratch_dir: &Path,
) -> Result<PreviewFrame> {
    let state = seeded_pet_state(ctx);
    render_watch_frame_from_state(
        ctx,
        scratch_dir,
        WatchFrameFixture {
            id,
            title,
            width,
            height,
            state: &state,
            now: ctx.fixed_now,
        },
    )
}

pub(crate) fn render_watch_frame_from_state(
    ctx: &PreviewRenderContext,
    scratch_dir: &Path,
    fixture: WatchFrameFixture<'_>,
) -> Result<PreviewFrame> {
    let WatchFrameFixture {
        id,
        title,
        width,
        height,
        state,
        now,
    } = fixture;
    let usage_path = scratch_dir.join(format!("{id}.sqlite"));
    seed_usage_store(&usage_path, now)?;
    let render = RenderContext::with_clock(ctx.render.color_capability, WatchClock::fixed(now));
    let vm = build_watch_view_model_at(state, &usage_path, now, UtcOffset::UTC)?;
    let layout = layout_watch_with_context(Rect::new(0, 0, width, height), &vm, &render);

    let mut terminal = Terminal::new(TestBackend::new(width, height))?;
    terminal.draw(|frame| {
        render_watch_frame_with_layout(frame, &vm, &render, &layout);
    })?;

    let mut frame = frame_from_buffer(id, title, terminal.backend().buffer());
    frame.layout = Some(preview_layout(id, &layout));
    Ok(frame)
}

fn seeded_pet_state(ctx: &PreviewRenderContext) -> PetState {
    let mut state = PetState::new_for_test("glorp-preview-watch", "Mochi");
    state.pet.generated_species = Species::Fuzz;
    state.stage = Stage::S4;
    state.xp = 8.5;
    state.lifetime_effective_tokens = 125_000.0;
    state.vitals = Vitals {
        fed: 70.0,
        happiness: 72.0,
        energy: 68.0,
    };
    state.created_at = ctx.fixed_now - Duration::days(18);
    state.last_updated_at = ctx.fixed_now;
    state.last_usage_poll_at = Some(ctx.fixed_now - Duration::minutes(5));
    // Hand-seed a few narrative entries for visual review. In production these
    // are auto-generated by the narration system; here we demonstrate the feed
    // layout with a fixed set so the snapshot is stable and reviewable.
    state.recent_events = vec![
        NarrativeEvent {
            observed_at: ctx.fixed_now - Duration::minutes(15),
            text: format!("{} brightened", state.pet.accepted_name),
        },
        NarrativeEvent {
            observed_at: ctx.fixed_now - Duration::minutes(10),
            text: format!("{} munched", state.pet.accepted_name),
        },
        NarrativeEvent {
            observed_at: ctx.fixed_now - Duration::minutes(2),
            text: format!(
                "{} evolved into {}",
                state.pet.accepted_name,
                crate::pet::art::stage_label(state.pet.generated_species, state.stage)
            ),
        },
    ];
    state.habitat.earned_props = vec![
        EarnedHabitatProp {
            id: HabitatPropId::new("codex_signal_lamp"),
            earned_at: ctx.fixed_now - Duration::days(12),
            source: HabitatPropSource::ProviderFirstUse {
                provider_surface: "codex".to_string(),
            },
        },
        EarnedHabitatProp {
            id: HabitatPropId::new("heavy_session_planter"),
            earned_at: ctx.fixed_now - Duration::days(6),
            source: HabitatPropSource::HeavySession,
        },
        EarnedHabitatProp {
            id: HabitatPropId::new("token_pebble_25k"),
            earned_at: ctx.fixed_now - Duration::days(10),
            source: HabitatPropSource::LifetimeTokens {
                threshold: 25_000.0,
            },
        },
        EarnedHabitatProp {
            id: HabitatPropId::new("token_shell_100k"),
            earned_at: ctx.fixed_now - Duration::days(4),
            source: HabitatPropSource::LifetimeTokens {
                threshold: 100_000.0,
            },
        },
    ];
    state
}

fn seed_usage_store(path: &Path, now: OffsetDateTime) -> Result<()> {
    let mut usage = UsageStore::open(path)?;
    for (surface, observed_at, effective_tokens, model) in [
        (
            "claude-code",
            now - Duration::minutes(5),
            12_500.0,
            "claude-sonnet",
        ),
        ("codex", now - Duration::minutes(8), 4_200.0, "gpt-5-codex"),
        (
            "claude-code",
            now - Duration::days(1),
            8_800.0,
            "claude-sonnet",
        ),
    ] {
        usage.insert_event(&NormalizedUsageEvent {
            provider_surface: surface.to_string(),
            model: Some(model.to_string()),
            provider_delta_id: Some(format!("preview-{surface}-{effective_tokens}")),
            ..NormalizedUsageEvent::for_test_at(observed_at, effective_tokens)
        })?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn watch_frames_include_wide_tall_wide_and_compact() {
        let dir = tempfile::tempdir().unwrap();
        let ctx = PreviewRenderContext::deterministic();

        let frames = watch_frames(&ctx, dir.path()).unwrap();

        assert_eq!(frames.len(), 3);
        assert_eq!(frames[0].id, "watch-wide-normal");
        assert_eq!((frames[0].width, frames[0].height), (120, 32));
        assert_eq!(frames[1].id, "watch-tall-wide");
        assert_eq!((frames[1].width, frames[1].height), (180, 50));
        assert_eq!(frames[2].id, "watch-compact-normal");
        assert_eq!((frames[2].width, frames[2].height), (72, 24));
    }

    #[test]
    fn watch_frames_are_stable_for_fixed_time() {
        let first_dir = tempfile::tempdir().unwrap();
        let second_dir = tempfile::tempdir().unwrap();
        let ctx = PreviewRenderContext::deterministic();

        let first = watch_frames(&ctx, first_dir.path()).unwrap();
        let second = watch_frames(&ctx, second_dir.path()).unwrap();

        assert_eq!(first, second);
    }
}
