import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const script = path.join(repoRoot, "scripts/assert-release-version.mjs");

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + "\n");
}

function writeFixture({ version = "0.1.6", cargoVersion = version, platformVersions = {} } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "glorp-release-version-"));

  fs.writeFileSync(
    path.join(root, "Cargo.toml"),
    `[package]
name = "glorp"
version = "${cargoVersion}"
edition = "2021"
`
  );
  fs.writeFileSync(
    path.join(root, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "glorp"
version = "${cargoVersion}"
`
  );

  const platforms = ["darwin-arm64", "darwin-x64", "linux-arm64", "linux-x64", "win32-x64"];
  const optionalDependencies = Object.fromEntries(
    platforms.map((platform) => [`@arittr/glorp-${platform}`, version])
  );

  writeJson(path.join(root, "npm/glorp/package.json"), {
    name: "@arittr/glorp",
    version,
    optionalDependencies
  });
  writeJson(path.join(root, "package-lock.json"), {
    name: "glorp",
    lockfileVersion: 3,
    packages: {
      "npm/glorp": {
        name: "@arittr/glorp",
        version,
        optionalDependencies
      }
    }
  });

  for (const platform of platforms) {
    writeJson(path.join(root, "npm/platform", platform, "package.json"), {
      name: `@arittr/glorp-${platform}`,
      version: platformVersions[platform] ?? version
    });
  }

  return root;
}

function run(root, args = []) {
  return spawnSync(process.execPath, [script, "--repo-root", root, ...args], {
    encoding: "utf8"
  });
}

describe("assert-release-version", () => {
  it("passes when Cargo, npm, platform packages, lockfile, and tag agree", () => {
    const root = writeFixture();

    const result = run(root, ["--tag", "v0.1.6"]);

    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /release versions ok: 0\.1\.6/);
  });

  it("fails when Cargo.toml drifts from the npm release version", () => {
    const root = writeFixture({ cargoVersion: "0.1.0" });

    const result = run(root, ["--tag", "v0.1.6"]);

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /Cargo\.toml version 0\.1\.0 does not match expected 0\.1\.6/);
  });

  it("fails when a platform package drifts from the tag", () => {
    const root = writeFixture({ platformVersions: { "linux-x64": "0.1.5" } });

    const result = run(root, ["--tag", "v0.1.6"]);

    assert.notEqual(result.status, 0);
    assert.match(
      result.stderr,
      /npm\/platform\/linux-x64\/package\.json version 0\.1\.5 does not match expected 0\.1\.6/
    );
  });
});
