import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { it } from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const bumpScript = path.join(repoRoot, "scripts/bump-npm-version.mjs");
const assertScript = path.join(repoRoot, "scripts/assert-release-version.mjs");

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + "\n");
}

function writeFixture(version = "0.1.0") {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "glorp-bump-version-"));
  const platforms = ["darwin-arm64", "darwin-x64", "linux-arm64", "linux-x64", "win32-x64"];
  const optionalDependencies = Object.fromEntries(
    platforms.map((platform) => [`@arittr/glorp-${platform}`, version])
  );

  fs.writeFileSync(
    path.join(root, "Cargo.toml"),
    `[package]
name = "glorp"
version = "${version}"
edition = "2021"
`
  );
  fs.writeFileSync(
    path.join(root, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "glorp"
version = "${version}"
`
  );
  writeJson(path.join(root, "npm/glorp/package.json"), {
    name: "@arittr/glorp",
    version,
    optionalDependencies
  });
  writeJson(path.join(root, "package-lock.json"), {
    name: "glorp",
    lockfileVersion: 3,
    packages: {
      "node_modules/@arittr/glorp-linux-x64": {
        version,
        optional: true
      },
      "npm/glorp": {
        name: "@arittr/glorp",
        version,
        optionalDependencies
      },
      "npm/glorp/node_modules/@arittr/glorp-linux-x64": {
        optional: true
      }
    }
  });

  for (const platform of platforms) {
    writeJson(path.join(root, "npm/platform", platform, "package.json"), {
      name: `@arittr/glorp-${platform}`,
      version
    });
  }

  return root;
}

it("bumps every release version surface together", () => {
  const root = writeFixture();

  const bump = spawnSync(process.execPath, [bumpScript, "--repo-root", root, "0.2.0"], {
    encoding: "utf8"
  });
  assert.equal(bump.status, 0, bump.stderr);

  const check = spawnSync(process.execPath, [assertScript, "--repo-root", root, "--tag", "v0.2.0"], {
    encoding: "utf8"
  });
  assert.equal(check.status, 0, check.stderr);
});
